---

- name: "Join swarm as a worker"
  shell: >
    docker swarm join \
      {% if docker_swarm_drain == true %}--availability drain {% endif %}\
      --token "{{ docker_swarm_token_worker }}" \
      --advertise-addr="{{ docker_swarm_iface | default(ansible_default_ipv4.interface) }}" \
      "{{ docker_swarm_mgr_primary }}:2377" \
    && sleep 10

- name: "Gather current engine state"
  include_tasks: "common_state.yml"

- name: "Verify node is a worker"
  fail:
    msg: "Node does not appear to be a worker"
  when:
  - "docker_swarm_status != 'worker'"

- name: "Verify node connected on manager as worker"
  shell: >
    docker node inspect --format {% raw %}'{{.Spec.Role}},{{.Status.State}}{{if eq .Spec.Role "manager"}},{{.ManagerStatus.Reachability}}{{end}}'{% endraw %} '{{ docker_swarm_node_id }}'
  delegate_to: "{{groups['docker_swarm_mgr'][0]}}"
  register: docker_swarm_mgr_node_status
  failed_when: >
    (docker_swarm_mgr_node_status.rc != 0) or
    ('worker,ready' not in docker_swarm_mgr_node_status.stdout)
  retries: 5
  delay: 5
  changed_when: false

